pipeline {

  agent any

  environment {
    APP_IMAGE = "python-app:ci"
  }

  stages {

    /* =========================
       CI
       ========================= */

    stage('CI - Unit tests') {
      agent {
        docker {
          image 'python:3.6-slim'
        }
      }
      steps {
        sh '''
          python --version
          pip install -r requirements.txt
          pytest
        '''
      }
    }

    stage('CI - Docker build') {
      steps {
        sh '''
          docker build -t ${APP_IMAGE} -f devops/Dockerfile .
        '''
      }
    }

    /* =========================
       CD (solo ramas principales)
       ========================= */

    stage('CD - Deploy (docker compose)') {
      when {
        anyOf {
          branch 'develop'
          branch 'master'
        }
      }
      steps {
        sh '''
          docker compose up -d
        '''
      }
    }

    stage('CD - E2E test') {
      when {
        anyOf {
          branch 'develop'
          branch 'master'
        }
      }
      steps {
        sh '''
          sleep 5
          curl -f http://localhost:5001
        '''
      }
    }
  }

  /* =========================
     LIMPIEZA
     ========================= */

  post {
    always {
      sh '''
        docker compose down --volumes || true
      '''
    }
  }
}

